spring.application.name=roasted-by-fda

spring.datasource.url=jdbc:postgresql://localhost:5432/roasted_fda
spring.datasource.username=${DB_USER:fda_user}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080